# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-21 09:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Desc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.TextField(verbose_name='Описание')),
            ],
        ),
        migrations.CreateModel(
            name='EmailToContractor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время изменения')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('noreply', models.BooleanField(default=False, verbose_name='Не писать')),
                ('wrong', models.BooleanField(default=False, verbose_name='Неверный')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Изменил')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('desc_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.Desc')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время изменения')),
                ('latitude', models.FloatField(verbose_name='Широта')),
                ('longitude', models.FloatField(verbose_name='Долгота')),
                ('street', models.TextField(verbose_name='Улица, дом/строение')),
                ('city', models.CharField(max_length=128, verbose_name='Город')),
                ('region', models.CharField(max_length=128, verbose_name='Область')),
                ('zipcode', models.IntegerField(verbose_name='Индекс')),
                ('country', models.CharField(max_length=128, verbose_name='Страна')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Изменил')),
            ],
            options={
                'abstract': False,
            },
            bases=('core.desc', models.Model),
        ),
        migrations.CreateModel(
            name='Named',
            fields=[
                ('desc_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.Desc')),
                ('name', models.TextField(verbose_name='Наименование')),
            ],
            bases=('core.desc',),
        ),
        migrations.CreateModel(
            name='Contractor',
            fields=[
                ('named_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.Named')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время изменения')),
                ('cite', models.URLField(verbose_name='Сайт')),
                ('phone', models.CharField(max_length=128, verbose_name='Телефон')),
                ('fax', models.CharField(max_length=128, verbose_name='Факс')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.EmailToContractor')),
                ('emails', models.ManyToManyField(related_name='_contractor_emails_+', to='core.EmailToContractor', verbose_name='Emails')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Изменил')),
            ],
            options={
                'abstract': False,
            },
            bases=('core.named', models.Model),
        ),
    ]
