# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-28 09:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='время изменения')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='описание')),
                ('street', models.TextField(blank=True, null=True, verbose_name='улица, дом/строение')),
                ('city', models.CharField(max_length=128, verbose_name='город')),
                ('region', models.CharField(blank=True, max_length=128, null=True, verbose_name='область')),
                ('zipcode', models.IntegerField(blank=True, null=True, verbose_name='индекс')),
                ('country', models.CharField(blank=True, max_length=128, null=True, verbose_name='страна')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='создал')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='изменил')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Contractor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='время изменения')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='описание')),
                ('name', models.TextField(verbose_name='наименование')),
                ('cite', models.URLField(blank=True, null=True, verbose_name='сайт')),
                ('phone', models.CharField(max_length=128, verbose_name='телефон')),
                ('fax', models.CharField(blank=True, max_length=128, null=True, verbose_name='факс')),
                ('addresses', models.ManyToManyField(related_name='_contractor_addresses_+', to='core.Address', verbose_name='адреса')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='создал')),
            ],
            options={
                'verbose_name_plural': 'контрагенты',
                'verbose_name': 'контрагент',
            },
        ),
        migrations.CreateModel(
            name='EmailToContractor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='время изменения')),
                ('email', models.EmailField(max_length=254, verbose_name='эл. адрес')),
                ('noreply', models.BooleanField(default=False, verbose_name='не писать')),
                ('wrong', models.BooleanField(default=False, verbose_name='неверный')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='создал')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='изменил')),
            ],
            options={
                'verbose_name_plural': 'эл. адреса',
                'verbose_name': 'эл. адрес',
            },
        ),
        migrations.AddField(
            model_name='contractor',
            name='emails',
            field=models.ManyToManyField(related_name='_contractor_emails_+', to='core.EmailToContractor', verbose_name='эл. адреса'),
        ),
        migrations.AddField(
            model_name='contractor',
            name='primary_address',
            field=models.ForeignKey(blank=True, help_text='перед тем как задать главный адрес добавьте его и перезагрузите страницу.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.Address', verbose_name='адрес'),
        ),
        migrations.AddField(
            model_name='contractor',
            name='primary_email',
            field=models.ForeignKey(blank=True, help_text='перед тем как задать главный email добавьте его и перезагрузите страницу.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.EmailToContractor', verbose_name='эл. адрес'),
        ),
        migrations.AddField(
            model_name='contractor',
            name='updated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='изменил'),
        ),
    ]
