# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-28 10:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_auto_20160528_0928'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name': 'адрес', 'verbose_name_plural': 'адреса'},
        ),
        migrations.AddField(
            model_name='contractor',
            name='annual_income',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='годовой доход'),
        ),
        migrations.AddField(
            model_name='contractor',
            name='annual_income_currency',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='валюта'),
        ),
        migrations.AddField(
            model_name='contractor',
            name='employee_num',
            field=models.IntegerField(blank=True, null=True, verbose_name='число сотрудников'),
        ),
        migrations.AddField(
            model_name='contractor',
            name='kind',
            field=models.CharField(blank=True, max_length=24, null=True, verbose_name='тип контрагента'),
        ),
        migrations.AddField(
            model_name='contractor',
            name='own',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='собственность'),
        ),
        migrations.AddField(
            model_name='contractor',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Contractor', verbose_name='состоит в'),
        ),
        migrations.AddField(
            model_name='contractor',
            name='rating',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='рейтинг'),
        ),
        migrations.AddField(
            model_name='contractor',
            name='responsible',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Ответственный'),
        ),
        migrations.AddField(
            model_name='contractor',
            name='sector',
            field=models.CharField(blank=True, max_length=24, null=True, verbose_name='отрасль'),
        ),
        migrations.AddField(
            model_name='contractor',
            name='sic',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='ОКВЭД/SIC'),
        ),
        migrations.AddField(
            model_name='contractor',
            name='stock_code',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='биржевой код'),
        ),
    ]
