# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-09 19:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0003_auto_20160528_1024'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='время изменения')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='описание')),
                ('name', models.TextField(verbose_name='наименование')),
                ('position', models.CharField(blank=True, max_length=256, null=True, verbose_name='должность')),
                ('department', models.CharField(blank=True, max_length=256, null=True, verbose_name='отдел')),
                ('phone_work', models.CharField(blank=True, max_length=128, null=True, verbose_name='телефон (раб.)')),
                ('phone_mobile', models.CharField(blank=True, max_length=128, null=True, verbose_name='телефон (моб.)')),
                ('fax', models.CharField(blank=True, max_length=128, null=True, verbose_name='факс')),
                ('src', models.CharField(blank=True, choices=[('phone', 'холодный прозвон'), ('existing_client', 'существующий клиент'), ('own', 'собственный'), ('employee', 'сотрудник'), ('pr', 'pr-деятельность'), ('direct_link', 'прямая ссылка'), ('conference', 'конференция'), ('special_galery', 'спец. выставка'), ('web', 'сайт'), ('talk', 'разговор'), ('email', 'Email'), ('marketing', 'маркетинговая кампания')], max_length=128, null=True, verbose_name='источник')),
                ('addresses', models.ManyToManyField(related_name='_contact_addresses_+', to='core.Address', verbose_name='адреса')),
            ],
            options={
                'verbose_name': 'контакт',
                'verbose_name_plural': 'контакты',
            },
        ),
        migrations.AlterField(
            model_name='contractor',
            name='responsible',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ответственный'),
        ),
        migrations.AddField(
            model_name='contact',
            name='contractor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Contractor', verbose_name='контрагент'),
        ),
        migrations.AddField(
            model_name='contact',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='создал'),
        ),
        migrations.AddField(
            model_name='contact',
            name='emails',
            field=models.ManyToManyField(related_name='_contact_emails_+', to='core.EmailToContractor', verbose_name='эл. адреса'),
        ),
        migrations.AddField(
            model_name='contact',
            name='head',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Contact', verbose_name='руководитель'),
        ),
        migrations.AddField(
            model_name='contact',
            name='primary_address',
            field=models.ForeignKey(blank=True, help_text='перед тем как задать главный адрес добавьте его и перезагрузите страницу.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.Address', verbose_name='адрес'),
        ),
        migrations.AddField(
            model_name='contact',
            name='primary_email',
            field=models.ForeignKey(blank=True, help_text='перед тем как задать главный email добавьте его и перезагрузите страницу.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.EmailToContractor', verbose_name='эл. адрес'),
        ),
        migrations.AddField(
            model_name='contact',
            name='responsible',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ответственный'),
        ),
        migrations.AddField(
            model_name='contact',
            name='updated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='изменил'),
        ),
    ]
