# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-09 23:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0004_auto_20160609_1902'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='время изменения')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='описание')),
                ('name', models.CharField(max_length=192, verbose_name='наименование')),
                ('src', models.CharField(blank=True, choices=[('phone', 'холодный прозвон'), ('existing_client', 'существующий клиент'), ('own', 'собственный'), ('employee', 'сотрудник'), ('pr', 'pr-деятельность'), ('direct_link', 'прямая ссылка'), ('conference', 'конференция'), ('special_galery', 'спец. выставка'), ('web', 'сайт'), ('talk', 'разговор'), ('email', 'Email'), ('marketing', 'маркетинговая кампания')], max_length=128, null=True, verbose_name='источник')),
                ('src_desc', models.TextField(blank=True, null=True, verbose_name='описание источника пред. контакта')),
                ('currency', models.CharField(blank=True, choices=[('rubles', 'рубли')], max_length=16, null=True, verbose_name='валюта')),
                ('amount', models.DecimalField(decimal_places=8, max_digits=32, verbose_name='сумма сделки')),
                ('stage', models.CharField(choices=[('Account is liquidated', 'Счёт оплачен'), ('Assembling', 'Сборка заказа / Счёт оплачен'), ('Assembling1', 'Сборка заказа / Счёт частично оплачен'), ('Assembling2', 'Сборка заказа / Счёт не оплачен'), ('Shipping0', 'Частичная готовность к отгрузке'), ('Shipping', 'Готовность к отгрузке'), ('Shipping1', 'Заказ отгружен / Счёт частично оплачен'), ('Shipping2', 'Заказ отгружен / Счёт не оплачен'), ('Prospecting', 'Разведка'), ('Qualification', 'Оценка'), ('Needs Analysis', 'Анализ потребностей'), ('Value Proposition', 'Предложение ценности'), ('Id. Decision Makers', 'Опред. лиц, принимающих решения'), ('Perception Analysis', 'Анализ реакции'), ('Proposal/Price Quote', 'Ком. предложение /Выставление счёта'), ('Negotiation/Review', 'Согласование / Пересмотр'), ('Closed Won', 'Закрыто с успехом / Товар отгружен'), ('Closed Lost', 'Закрыто с потерями / Товар возвращён')], max_length=32, verbose_name='стадия продаж')),
                ('posibility', models.IntegerField(blank=True, null=True, verbose_name='вероятность (%)')),
                ('next_step', models.CharField(blank=True, max_length=128, null=True, verbose_name='следующий шаг')),
                ('closing_date', models.DateField(verbose_name='ожидаемая дата закрытия')),
                ('kind', models.CharField(blank=True, choices=[('existing', 'существующий бизнес'), ('new', 'новый бизнес')], max_length=16, null=True, verbose_name='тип')),
            ],
            options={
                'verbose_name': 'сделка',
                'verbose_name_plural': 'сделки',
            },
        ),
        migrations.CreateModel(
            name='MarketingCampaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='время изменения')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='описание')),
                ('name', models.CharField(max_length=192, verbose_name='наименование')),
                ('opening_date', models.DateField(blank=True, null=True, verbose_name='дата начала')),
                ('closing_date', models.DateField(verbose_name='дата окончания')),
                ('currency', models.CharField(blank=True, choices=[('rubles', 'рубли')], max_length=16, null=True, verbose_name='валюта')),
                ('budget', models.DecimalField(blank=True, decimal_places=8, max_digits=32, null=True, verbose_name='бюджет')),
                ('expected_amount', models.DecimalField(blank=True, decimal_places=8, max_digits=32, null=True, verbose_name='ожидаемая стоимость')),
                ('actual_amount', models.DecimalField(blank=True, decimal_places=8, max_digits=32, null=True, verbose_name='фактическая стоимость')),
                ('expected_revenue', models.DecimalField(blank=True, decimal_places=8, max_digits=32, null=True, verbose_name='ожидаемый доход')),
                ('target', models.TextField(blank=True, null=True, verbose_name='цель')),
                ('status', models.CharField(blank=True, choices=[('Planning', 'Планируется'), ('Active', 'Активна'), ('Inactive', 'Не активна'), ('Complete', 'Завершена'), ('In Queue', 'В очереди'), ('Sending', 'Отсылается')], max_length=16, null=True, verbose_name='статус')),
                ('kind', models.CharField(blank=True, choices=[('Telesales', 'Продажи по телефону'), ('Mail', 'Почтовая рассылка'), ('Email', 'Рассылка E-mail'), ('Print', 'Печать'), ('Web', 'Веб-реклама'), ('Radio', 'Радио'), ('Television', 'Телевидение'), ('NewsLetter', 'Информ. бюллетень')], max_length=16, null=True, verbose_name='тип')),
                ('number_of_impressions', models.IntegerField(blank=True, null=True, verbose_name='количество показов')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='создал')),
                ('responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ответственный')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='изменил')),
            ],
            options={
                'verbose_name': 'маркетинговая кампания',
                'verbose_name_plural': 'маркетинговые кампании',
            },
        ),
        migrations.CreateModel(
            name='PreliminaryContact',
            fields=[
                ('contact_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.Contact')),
                ('status', models.CharField(blank=True, choices=[('New', 'Новый'), ('Assigned', 'Назначенный'), ('In Process', 'В процессе'), ('Converted', 'Преобразован'), ('Recycled', 'Повторный'), ('Dead', 'Мёртвый')], max_length=32, null=True, verbose_name='статус')),
                ('status_desc', models.TextField(blank=True, null=True, verbose_name='описание статуса')),
                ('amount', models.DecimalField(blank=True, decimal_places=8, max_digits=32, null=True, verbose_name='сумма сделки')),
                ('transmitted_from', models.CharField(blank=True, max_length=128, null=True, verbose_name='передан от')),
            ],
            options={
                'verbose_name': 'предварительный контакт',
                'verbose_name_plural': 'предварительные контакты',
            },
            bases=('core.contact',),
        ),
        migrations.RemoveField(
            model_name='contact',
            name='name',
        ),
        migrations.AddField(
            model_name='contact',
            name='cite',
            field=models.URLField(blank=True, null=True, verbose_name='сайт'),
        ),
        migrations.AddField(
            model_name='contact',
            name='first_name',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='имя'),
        ),
        migrations.AddField(
            model_name='contact',
            name='last_name',
            field=models.CharField(default='AAA', max_length=64, verbose_name='фамилия'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='skype',
            field=models.URLField(blank=True, null=True, verbose_name='skype'),
        ),
        migrations.AddField(
            model_name='contact',
            name='src_desc',
            field=models.TextField(blank=True, null=True, verbose_name='описание источника пред. контакта'),
        ),
        migrations.AlterField(
            model_name='contractor',
            name='name',
            field=models.CharField(max_length=192, verbose_name='наименование'),
        ),
        migrations.AddField(
            model_name='deal',
            name='contractor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Contractor', verbose_name='контрагент'),
        ),
        migrations.AddField(
            model_name='deal',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='создал'),
        ),
        migrations.AddField(
            model_name='deal',
            name='marketing_campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.MarketingCampaign', verbose_name='маркетинговая кампания'),
        ),
        migrations.AddField(
            model_name='deal',
            name='responsible',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ответственный'),
        ),
        migrations.AddField(
            model_name='deal',
            name='updated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='изменил'),
        ),
        migrations.AddField(
            model_name='contact',
            name='marketing_campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.MarketingCampaign', verbose_name='маркетинговая кампания'),
        ),
        migrations.AddField(
            model_name='contractor',
            name='marketing_campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.MarketingCampaign', verbose_name='маркетинговая кампания'),
        ),
    ]
