# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-12 12:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0005_auto_20160609_2322'),
    ]

    operations = [
        migrations.CreateModel(
            name='Circulation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='время изменения')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='описание')),
                ('name', models.CharField(max_length=192, verbose_name='наименование')),
                ('priority', models.IntegerField(choices=[(0, 'Низкий'), (1, 'Средний'), (2, 'Высокий')], verbose_name='приоритет')),
                ('status', models.CharField(blank=True, choices=[('Open_New', 'Новое'), ('Open_Assigned', 'Назначенное'), ('Closed_Closed', 'Закрытое'), ('Open_Pending Input', 'Ожидание решения'), ('Closed_Rejected', 'Отклонённое'), ('Closed_Duplicate', 'Продублированное')], max_length=32, null=True, verbose_name='статус')),
                ('kind', models.CharField(choices=[('Administration', 'Административное'), ('Product', 'Продукция'), ('User', 'Пользовательское')], max_length=32, verbose_name='тип')),
                ('resolution', models.TextField(blank=True, null=True, verbose_name='резолюция')),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Contractor', verbose_name='контрагент')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='создал')),
                ('responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ответственный')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='изменил')),
            ],
            options={
                'verbose_name': 'обращение',
                'verbose_name_plural': 'обращения',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='время изменения')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='описание')),
                ('name', models.CharField(max_length=192, verbose_name='наименование')),
                ('attach', models.FileField(upload_to='documents', verbose_name='вложение')),
                ('version', models.IntegerField(default=1, verbose_name='версия')),
                ('kind', models.CharField(blank=True, choices=[('mailmerge', 'Слияние'), ('eula', 'Пользовательское соглашение (EULA)'), ('nda', 'Соглашение о неразглашении (NDA)'), ('license', 'Лицензионное соглашение')], max_length=16, null=True, verbose_name='тип документа')),
                ('status', models.CharField(choices=[('Active', 'Активен'), ('Draft', 'Черновик'), ('FAQ', 'ЧаВо'), ('Expired', 'Просрочен'), ('Under Review', 'На рассмотрении'), ('Pending', 'Ожидание решения')], max_length=16, verbose_name='статус')),
                ('is_template', models.BooleanField(default=False, verbose_name='шаблон')),
                ('publication_date', models.DateField(verbose_name='дата публикации')),
                ('expire_date', models.DateField(blank=True, null=True, verbose_name='актуален до')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='создал')),
                ('related_documents', models.ManyToManyField(blank=True, related_name='_document_related_documents_+', to='core.Document', verbose_name='связанный документ')),
                ('responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ответственный')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='изменил')),
            ],
            options={
                'verbose_name': 'документ',
                'verbose_name_plural': 'документы',
            },
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='время изменения')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='описание')),
                ('name', models.CharField(max_length=192, verbose_name='наименование')),
                ('starting_datetime', models.DateTimeField(verbose_name='дата и время')),
                ('duration', models.IntegerField(verbose_name='продолжительность')),
                ('status', models.CharField(choices=[('planned', 'запланирован'), ('held', 'состоялся'), ('not held', 'не состоялся')], max_length=32, verbose_name='статус')),
                ('place', models.CharField(blank=True, max_length=256, null=True, verbose_name='место встречи')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='создал')),
                ('responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ответственный')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='изменил')),
            ],
            options={
                'verbose_name': 'встреча',
                'verbose_name_plural': 'встречи',
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='время изменения')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='описание')),
                ('name', models.CharField(max_length=192, verbose_name='наименование')),
                ('attach', models.FileField(blank=True, null=True, upload_to='notes', verbose_name='вложение')),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Contact', verbose_name='контактное лицо')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='создал')),
                ('responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ответственный')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='изменил')),
            ],
            options={
                'verbose_name': 'заметка',
                'verbose_name_plural': 'заметки',
            },
        ),
        migrations.CreateModel(
            name='PhoneCall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='время изменения')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='описание')),
                ('name', models.CharField(max_length=192, verbose_name='наименование')),
                ('starting_datetime', models.DateTimeField(verbose_name='дата и время')),
                ('duration', models.IntegerField(verbose_name='продолжительность')),
                ('kind', models.CharField(choices=[('inbound', 'входящий'), ('outbound', 'исходящий')], max_length=16, verbose_name='тип')),
                ('status', models.CharField(choices=[('planned', 'запланирован'), ('held', 'состоялся'), ('not held', 'не состоялся')], max_length=32, verbose_name='статус')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='создал')),
                ('responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ответственный')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='изменил')),
            ],
            options={
                'verbose_name': 'звонок',
                'verbose_name_plural': 'звонки',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='время изменения')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='описание')),
                ('name', models.CharField(max_length=192, verbose_name='наименование')),
                ('starting_date', models.DateField(verbose_name='дата начала')),
                ('finishing_date', models.DateField(verbose_name='дата окончания')),
                ('priority', models.IntegerField(choices=[(0, 'Низкий'), (1, 'Средний'), (2, 'Высокий')], verbose_name='приоритет')),
                ('status', models.CharField(choices=[('Draft', 'Черновик'), ('In Review', 'На рассмотрении'), ('Published', 'Опубликован')], max_length=16, verbose_name='статус')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='создал')),
                ('responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ответственный')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='изменил')),
            ],
            options={
                'verbose_name': 'проект',
                'verbose_name_plural': 'проекты',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='время изменения')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='описание')),
                ('name', models.CharField(max_length=192, verbose_name='наименование')),
                ('starting_datetime', models.DateTimeField(verbose_name='дата и время')),
                ('duration', models.IntegerField(verbose_name='продолжительность')),
                ('priority', models.IntegerField(choices=[(0, 'Низкий'), (1, 'Средний'), (2, 'Высокий')], verbose_name='приоритет')),
                ('status', models.CharField(choices=[('Not Started', 'Не начата'), ('In Progress', 'В процессе'), ('Completed', 'Завершена'), ('Pending Input', 'Ожидание решения'), ('Deferred', 'Отложена')], max_length=32, verbose_name='статус')),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Contact', verbose_name='контактное лицо')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='создал')),
                ('responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ответственный')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='изменил')),
            ],
            options={
                'verbose_name': 'задача',
                'verbose_name_plural': 'задачи',
            },
        ),
    ]
