# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-19 22:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20160619_2113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='phonecall',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='task',
            name='duration',
        ),
        migrations.AddField(
            model_name='meeting',
            name='finishing_datetime',
            field=models.DateTimeField(default=datetime.datetime(2016, 6, 19, 21, 59, 49, 927469, tzinfo=utc), verbose_name='время окончания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='phonecall',
            name='finishing_datetime',
            field=models.DateTimeField(default=datetime.datetime(2016, 6, 19, 21, 59, 59, 478639, tzinfo=utc), verbose_name='время окончания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='finishing_datetime',
            field=models.DateTimeField(default=datetime.datetime(2016, 6, 19, 22, 0, 51, 409037, tzinfo=utc), verbose_name='время окончания'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='meeting',
            name='starting_datetime',
            field=models.DateTimeField(verbose_name='время начала'),
        ),
        migrations.AlterField(
            model_name='phonecall',
            name='starting_datetime',
            field=models.DateTimeField(verbose_name='время начала'),
        ),
        migrations.AlterField(
            model_name='task',
            name='starting_datetime',
            field=models.DateTimeField(verbose_name='время начала'),
        ),
    ]
